### ISSUE TITLE
OpenSSL issue with U-boot build

### ISSUE THREAD

**Issue by mstevanovic** [muvarov/meta-ts#2]
Hi @muvarov 

I have question about OpenSSL issue with U-boot build
https://github.com/muvarov/meta-ts/commit/ee080d5de8559a3751c288371a57a709dec34e1e

I am on kirsktone TAG 2022-04.1-kirkstone and I have this issue with U-Boot

Is there a some patch/workaround for this issue on kirsktone branch? Your master2 branch is look like branch to reproduce issue only
Do you have idea what is a root cause of this issue?

thanks a lot in advance

**Comment by muvarov** [comment]
@mstevanovic  we are working on fixing it. Update will be soon in  the main repo. i.e. https://gitlab.com/Linaro/trustedsubstrate/meta-ts
